QuanLyBanHang/Models/TaiKhoan.cs
using System;
using System.Collections.Generic;

namespace QuanLyBanHang.Models
{
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            Admin = new HashSet<Admin>();
            KhachHang = new HashSet<KhachHang>();
            NhanVien = new HashSet<NhanVien>();
        }

        public int TaiKhoanId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public DateTime? NgayTao { get; set; }
        public int VaiTroId { get; set; }

        public virtual VaiTro VaiTro { get; set; }
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}

QuanLyBanHang/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using QuanLyBanHang.Models;

namespace QuanLyBanHang.Controllers
{
    public class TaiKhoanController : Controller
    {


        private readonly QuanLyBanHangDbContext _context;

        public TaiKhoanController(QuanLyBanHangDbContext context)
        {
            _context = context;
        }

        // GET: TaiKhoan
        public async Task<IActionResult> Index()
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");
            var quanLyBanHangDbContext = _context.TaiKhoan.Include(t => t.VaiTro);
            return View(await quanLyBanHangDbContext.ToListAsync());
        }

        //Get:TaiKhoan/Admin-NhanVien
        [ServiceFilter(typeof(AdminFilter))]
        public IActionResult GetNhanVien(string id)
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");
            List<TaiKhoan> taikhoan = _context.TaiKhoan.ToList();
            List<VaiTro> vaitro = _context.VaiTro.ToList();
            List<NhanVien> nhanvien = _context.NhanVien.ToList();

            var taiKhoan_nhanvien = (from h in taikhoan
                                     join vtro in vaitro
                                     on h.VaiTroId equals vtro.VaiTroId into taikhoan_vaitro
                                     from vtro in taikhoan_vaitro.ToList()
                                     join nv in nhanvien
                                     on h.TaiKhoanId equals nv.TaiKhoanId into taikhoan_nhanvien
                                     from nv in taikhoan_nhanvien.ToList()
                                     where h.VaiTroId == 2

                                     select new TaiKhoan_NhanVien_KhachHang_Admin_VaiTro
                                     {
                                         taiKhoan = h,
                                         vaiTro = vtro,
                                         nhanVien = nv
                                     });

            if(!String.IsNullOrEmpty(id))
            {
                taiKhoan_nhanvien = taiKhoan_nhanvien.Where(search => search.nhanVien.HoTen.Contains(id));
            }
            taiKhoan_nhanvien = taiKhoan_nhanvien.ToList();

            return View(taiKhoan_nhanvien);
        }

        //Get:TaiKhoan/KhachHang
        public IActionResult GetKhachHang(string SearchString)
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");
            List<TaiKhoan> taikhoan = _context.TaiKhoan.ToList();
            List<VaiTro> vaitro = _context.VaiTro.ToList();
            List<KhachHang> khachhang = _context.KhachHang.ToList();

            var quanlykhachhang = (from h in taikhoan
                                   join vtro in vaitro
                                   on h.VaiTroId equals vtro.VaiTroId into taikhoan_vaitro
                                   from vtro in taikhoan_vaitro.ToList()
                                   join kh in khachhang
                                   on h.TaiKhoanId equals kh.TaiKhoanId into taikhoan_khachhang
                                   from kh in taikhoan_khachhang.ToList()
                                   where h.VaiTroId == 3
                                   select new TaiKhoan_NhanVien_KhachHang_Admin_VaiTro
                                   {
                                       taiKhoan = h,
                                       vaiTro = vtro,
                                       khachhang = kh
                                   });
            if (!String.IsNullOrEmpty(SearchString))
            {
               
                quanlykhachhang = quanlykhachhang.Where(search => search.khachhang.HoTen.ToLower().Contains(SearchString.ToLower()));
            }
            quanlykhachhang = quanlykhachhang.ToList();
            return View(quanlykhachhang);
        }
        //Get: TaiKhoan/Admin
        [ServiceFilter(typeof(AdminFilter))]
        public IActionResult GetAdmin(string SearchString)
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");

            List<TaiKhoan> taikhoan = _context.TaiKhoan.ToList();
            List<VaiTro> vaitro = _context.VaiTro.ToList();
            List<Admin> admin = _context.Admin.ToList();

            var quanlyadmin = (from h in taikhoan
                                   join vtro in vaitro
                                   on h.VaiTroId equals vtro.VaiTroId into taikhoan_vaitro
                                   from vtro in taikhoan_vaitro.ToList()
                                   join ad in admin
                                   on h.TaiKhoanId equals ad.TaiKhoanId into taikhoan_admin
                                   from ad in taikhoan_admin.ToList()
                                   where h.VaiTroId == 1
                                   select new TaiKhoan_NhanVien_KhachHang_Admin_VaiTro
                                   {
                                       taiKhoan = h,
                                       vaiTro = vtro,
                                       admin = ad
                                   });
            if (!String.IsNullOrEmpty(SearchString))
            {
                quanlyadmin = quanlyadmin.Where(search => search.admin.HoTen.ToLower().Contains(SearchString.ToLower()));
                quanlyadmin = quanlyadmin.ToList();
            }
            return View(quanlyadmin);
        }

    
       


        // GET: TaiKhoan/Edit/5
        public async Task<IActionResult> EditAdmin(int? id)
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");

            if (id == null)
            {
                return NotFound();
            }

            var taiKhoan = await _context.TaiKhoan.FindAsync(id);
            if (taiKhoan == null)
            {
                return NotFound();
            }
            ViewData["VaiTroId"] = new SelectList(_context.VaiTro, "VaiTroId", "VaiTroId", taiKhoan.VaiTroId);
            return View(taiKhoan);
        }

        // POST: TaiKhoan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAdmin(int id, [Bind("TaiKhoanId,Username,Password,NgayTao,VaiTroId")] TaiKhoan taiKhoan)
        {

            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");

            if (id != taiKhoan.TaiKhoanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    taiKhoan.NgayTao = DateTime.Now;
                    _context.Update(taiKhoan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaiKhoanExists(taiKhoan.TaiKhoanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(GetAdmin));
            }
            ViewData["VaiTroId"] = new SelectList(_context.VaiTro, "VaiTroId", "VaiTroId", taiKhoan.VaiTroId);
            return View(taiKhoan);
        }
        //nhan vien

        // GET: TaiKhoan/Edit/5
        public async Task<IActionResult> EditNhanVien(int? id)
        {
            TaiKhoan taiKhoanSession = JsonConvert.DeserializeObject<TaiKhoan>(HttpContext.Session.GetString("sessionUser"));
            ViewBag.UserName = taiKhoanSession.Username;
            ViewBag.VaiTroSession = HttpContext.Session.GetInt32("VaiTroSession");

            if (id == null)
            {
                return NotFound();
            }

            var taiKhoan = await _context.TaiKhoan.FindAsync(id);
            if (taiKhoan == null)
            {
                return NotFound();
            }
            ViewData["VaiTroId"] = new SelectList(_context.VaiTro, "VaiTroId", "VaiTroId", taiKhoan.VaiTroId);
            return View(taiKhoan);
        }

        // POST: TaiKhoan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

QuanLyBanHang/Views/TaiKhoan/Create.cshtml
@model QuanLyBanHang.Models.TaiKhoan

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>TaiKhoan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayTao" class="control-label"></label>
                <input asp-for="NgayTao" class="form-control" />
                <span asp-validation-for="NgayTao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VaiTroId" class="control-label"></label>
                <select asp-for="VaiTroId" class ="form-control" asp-items="ViewBag.VaiTroId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLyBanHang/Views/TaiKhoan/Delete.cshtml
@model QuanLyBanHang.Models.TaiKhoan

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VaiTro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VaiTro.VaiTroId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TaiKhoanId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

QuanLyBanHang/Views/TaiKhoan/Details.cshtml
@model QuanLyBanHang.Models.TaiKhoan

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VaiTro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VaiTro.VaiTroId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TaiKhoanId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QuanLyBanHang/Views/TaiKhoan/Edit.cshtml
@model QuanLyBanHang.Models.TaiKhoan

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>TaiKhoan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaiKhoanId" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgayTao" class="control-label"></label>
                <input asp-for="NgayTao" class="form-control" />
                <span asp-validation-for="NgayTao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VaiTroId" class="control-label"></label>
                <select asp-for="VaiTroId" class="form-control" asp-items="ViewBag.VaiTroId"></select>
                <span asp-validation-for="VaiTroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

QuanLyBanHang/Views/TaiKhoan/GetAdmin.cshtml
@model IEnumerable<QuanLyBanHang.Models.TaiKhoan_NhanVien_KhachHang_Admin_VaiTro>

@{
    ViewData["Title"] = "GetAdmin";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@section Links{
    <link rel="stylesheet" href="~/admin/custom/admin_users.css" />
    <link rel="stylesheet" href="~/admin/css/admin.css" />
}
<div class="background-popup">


</div>
<div class="container">
    <div class="header-content">
        <h2>Danh sách tài khoản</h2>

        <div class="header-event">
           

            <!-- 1. Đoạn cần thêm -->
            @using (Html.BeginForm("GetAdmin", "TaiKhoan", FormMethod.Get))
            {
                <p class="search">
                    Title: @Html.TextBox("SearchString")  <input type="submit" value="Tìm kiếm" id="search"/>
                </p>
            }
           @* <input type="text" id="SearchString" name="SearchString" class="col-sm-7" />
            <input type="submit" value="SearchString" />
            <a class="add-user btn" id="add-custom" asp-action="GetAdmin" Value="SearchString">
                <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                Tìm kiếm
            </a>*@
            <a class="add-user btn" id="add-admin">
                <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                Thêm tài khoản
            </a>

        </div>
    </div>
    <div class="content-content">
        <table class="table table-hover tm-table-small ">
            <thead>
                <tr>
                    <th scope="col"><input type="checkbox" id="checkall" /></th>
                    <th scope="col">Mã tài khoản</th>
                    <th scope="col">Họ và tên</th>
                    <th scope="col">Tên đăng nhập</th>
                    <th scope="col">Mật khẩu</th>
                    <th scope="col">Ngày tạo</th>
                    <th scope="col">Vai trò</th>
                    <th scope="col">Chức năng</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td scope="row"><input type="checkbox" class="tick" name="listadmin" value="@item.admin.Adminid" /></td>
                        <td>
                            @item.taiKhoan.TaiKhoanId
                        </td>
                        <td>
                            @item.admin.HoTen
                        </td>
                        <td>
                            @item.taiKhoan.Username
                        </td>
                        <td>
                            @item.taiKhoan.Password
                        </td>
                        <td>
                            @item.taiKhoan.NgayTao
                        </td>
                        <td>
                            @item.vaiTro.MoTa
                        </td>
                        <td>
                            <div>
                                <a onclick="Update(@item.admin.Adminid)" class="btn tm-product-delete-link" id="update-staff"><i class="fas fa-edit tm-product-delete-icon"></i></a>
                                <a onclick="Delete(@item.admin.Adminid)" class="tm-product-delete-link" id="delete-staff"><i class="far fa-trash-alt tm-product-delete-icon"></i></a>
                                <a onclick="Detail(@item.admin.Adminid)" class="btn tm-product-delete-link" id="detail-staff"><i class="fas fa-eye tm-product-delete-icon"></i></a>
                            </div>
                        </td>

                    </tr>

                }

            </tbody>
        </table>
    </div>


    <br />
    <br />
    <!-- table container -->

</div>


@section Scripts{
    <script src="~/admin/js/admin.js"></script>

}

QuanLyBanHang/Views/TaiKhoan/GetKhachHang.cshtml
@model IEnumerable<QuanLyBanHang.Models.TaiKhoan_NhanVien_KhachHang_Admin_VaiTro>

@{
    ViewData["Title"] = "GetKhachHang";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@section Links{
    <link rel="stylesheet" href="~/admin/custom/admin_users.css" />
    <link rel="stylesheet" href="~/admin/css/khachhang.css" />
}

<div class="background-popup">


</div>
<div class="container">
    <div class="header-content">
        <h2>Danh sách tài khoản</h2>

        <div class="header-event">
            @using (Html.BeginForm("GetKhachHang", "TaiKhoan", FormMethod.Get))
            {
                <p class="search">
                    Title: @Html.TextBox("SearchString")  <input type="submit" value="Tìm kiếm" id="search" />
                </p>
            }
            <a class="add-user btn" id="add-custom">
                <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                Thêm tài khoản
            </a>

        </div>
    </div>
    <div class="content-content">
        <table class="table table-hover tm-table-small ">
            <thead>
                <tr>
                    <th scope="col"><input type="checkbox" id="checkall" /></th>
                    <th scope="col">Mã tài khoản</th>
                    <th scope="col">Họ và tên</th>
                    <th scope="col">Tên đăng nhập</th>
                    <th scope="col">Mật khẩu</th>
                    <th scope="col">Ngày tạo</th>
                    <th scope="col">Vai trò</th>
                    <th scope="col">Chức năng</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td scope="row"><input type="checkbox" class="tick" name="listcustom" value="@item.khachhang.KhachHangId" /></td>
                    <td>
                        @item.taiKhoan.TaiKhoanId
                    </td>
                    <td>
                        @item.khachhang.HoTen
                    </td>
                    <td>
                        @item.taiKhoan.Username
                    </td>
                    <td>
                        @item.taiKhoan.Password
                    </td>
                    <td>
                        @item.taiKhoan.NgayTao
                    </td>
                    <td>
                        @item.vaiTro.MoTa
                    </td>
                    <td>
                        <div>
                            <a onclick="Update(@item.khachhang.KhachHangId)" class="btn tm-product-delete-link" id="update-staff"><i class="fas fa-edit tm-product-delete-icon"></i></a>
                            <a onclick="Delete(@item.khachhang.KhachHangId)" class="tm-product-delete-link" id="delete-staff"><i class="far fa-trash-alt tm-product-delete-icon"></i></a>
                            <a onclick="Detail(@item.khachhang.KhachHangId)" class="btn tm-product-delete-link" id="detail-staff"><i class="fas fa-eye tm-product-delete-icon"></i></a>
                        </div>
                    </td>

                </tr>

                }

            </tbody>
        </table>
    </div>


    <br />
    <br />
    <!-- table container -->

</div>


@section Scripts{
    <script src="~/admin/js/khachhang.js"></script>

}

QuanLyBanHang/Views/TaiKhoan/GetNhanVien.cshtml
@model IEnumerable<QuanLyBanHang.Models.TaiKhoan_NhanVien_KhachHang_Admin_VaiTro>
@{
    ViewData["Title"] = "GetAdmin_NhanVien";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@section Links{
    <link rel="stylesheet" href="~/admin/custom/admin_users.css" />
    <link rel="stylesheet" href="~/admin/css/nhanvien.css" />
}

<div class="background-popup">


</div>
<div class="container">
    <div class="header-content">
        <h2>Danh sách tài khoản</h2>
        <div class="header-event">
            @using (Html.BeginForm("GetNhanVien", "TaiKhoan", FormMethod.Get))
            {
                <p class="search">
                    Title: @Html.TextBox("SearchString")  <input type="submit" value="Tìm kiếm" id="search" />
                </p>
            }
            <a class="add-user btn" id="add-staff">
                <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                Thêm tài khoản
            </a>

        </div>
    </div>
    <div class="content-content">
        <table class="table table-hover tm-table-small ">
            <thead>
                <tr>
                    <th scope="col"><input type="checkbox" id="checkall" /></th>
                    <th scope="col">Mã tài khoản</th>
                    <th scope="col">Họ và tên</th>
                    <th scope="col">Tên đăng nhập</th>
                    <th scope="col">Mật khẩu</th>
                    <th scope="col">Ngày tạo</th>
                    <th scope="col">Vai trò</th>
                    <th scope="col">Chức năng</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td scope="row"><input type="checkbox" class="tick" name="liststaff" value="@item.nhanVien.NhanVienId" /></td>
                    <td>
                        @item.taiKhoan.TaiKhoanId
                    </td>
                    <td>
                        @item.nhanVien.HoTen
                    </td>
                    <td>
                        @item.taiKhoan.Username
                    </td>
                    <td>
                        @item.taiKhoan.Password
                    </td>
                    <td>
                        @item.taiKhoan.NgayTao
                    </td>
                    <td>
                        @item.vaiTro.MoTa
                    </td>

                    <td>
                        <div>
                            <a onclick="Update(@item.nhanVien.NhanVienId)" class="btn tm-product-delete-link" id="update-staff"><i class="fas fa-edit tm-product-delete-icon"></i></a>
                            <a onclick="Delete(@item.nhanVien.NhanVienId)" class="tm-product-delete-link" id="delete-staff"><i class="far fa-trash-alt tm-product-delete-icon"></i></a>
                            <a onclick="Detail(@item.nhanVien.NhanVienId)" class="btn tm-product-delete-link" id="detail-staff"><i class="fas fa-eye tm-product-delete-icon"></i></a>
                        </div>
                    </td>

                </tr>

                }

            </tbody>
        </table>
    </div>


    <br />
    <br />
    <!-- table container -->

</div>


@section Scripts{
    <script src="~/admin/js/nhanvien.js"></script>

}

QuanLyBanHang/Views/TaiKhoan/Index.cshtml
@model IEnumerable<QuanLyBanHang.Models.TaiKhoan>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayTao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VaiTro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayTao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VaiTro.VaiTroId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TaiKhoanId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TaiKhoanId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TaiKhoanId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>